# Generated by Django 6.0 on 2026-01-08 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_productimage_image'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE store_customer ALTER COLUMN first_name DROP NOT NULL;
                ALTER TABLE store_customer ALTER COLUMN last_name DROP NOT NULL;
                ALTER TABLE store_customer ALTER COLUMN email DROP NOT NULL;
            """,
            reverse_sql="""
                ALTER TABLE store_customer ALTER COLUMN first_name SET NOT NULL;
                ALTER TABLE store_customer ALTER COLUMN last_name SET NOT NULL;
                ALTER TABLE store_customer ALTER COLUMN email SET NOT NULL;
            """
        ),
    ]
