# Generated by Django 6.0 on 2025-12-22 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_order_options_alter_customer_birth_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('view_history', 'can view history')]},
        ),
    ]
