# Generated by Django 6.0 on 2026-05-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_customer_phone_alter_product_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
    ]
