# Generated by Django 6.0 on 2026-05-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_address_postal_code_address_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('P', 'pending'), ('C', 'confirmed'), ('PR', 'processing'), ('S', 'shipped'), ('D', 'delivered'), ('CX', 'cancelled')], default='P', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('S', 'esewa'), ('K', 'khalti'), ('COD', 'cash on delivery')], default='COD', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('P', 'pending'), ('C', 'complete'), ('F', 'failed'), ('COD', 'cash on delivery')], default='P', max_length=20),
        ),
    ]
