# Generated by Django 6.0 on 2026-05-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_order_order_status_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('S', 'esewa'), ('COD', 'cash on delivery')], max_length=20),
        ),
    ]
