# Generated by Django 6.0 on 2025-12-25 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='Image',
            new_name='image',
        ),
    ]
