# Generated by Django 6.0 on 2026-05-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cached_total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
