"""
Django settings for storefront project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent.parent
load_dotenv(BASE_DIR / '.env')


DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get("CLOUDINARYNAME"),
    'API_KEY': os.environ.get("CLOUDINARYAPIKEY"),
    'API_SECRET': os.environ.get("CLOUDINARYSECRETKEY"),
}

import cloudinary
cloudinary.config(
  cloud_name = os.environ.get("CLOUDINARYNAME"),
  api_key = os.environ.get("CLOUDINARYAPIKEY"),
  api_secret = os.environ.get("CLOUDINARYSECRETKEY"),
  secure = True
)



# Build paths inside the project like this: BASE_DIR / 'subdir'.


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!


DEBUG = os.getenv('DEBUG', 'False') == 'True'
SECRET_KEY = os.getenv('SECRET_KEY')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.sessions',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django_filters',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'djoser',
    'silk',
    'playground',
    'store',
    'tag',
    'likes',
    'core',
    "corsheaders",
    'cloudinary',
    'cloudinary_storage',
]




MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
if DEBUG:
    MIDDLEWARE+=['silk.middleware.SilkyMiddleware']
    

INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]


ROOT_URLCONF = 'storefront.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'storefront.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT=os.path.join(BASE_DIR,'staticfiles')

MEDIA_URL = '/media/'




# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
REST_FRAMEWORK={'COERCE_DECIMAL_TO_STRING':False,
                'DEFAULT_AUTHENTICATION_CLASSES': (
                'rest_framework_simplejwt.authentication.JWTAuthentication',
       
                ),
               
                }
SIMPLE_JWT = {
   'AUTH_HEADER_TYPES': ('JWT',),
   "ACCESS_TOKEN_LIFETIME": timedelta(days=5),
}

AUTH_USER_MODEL='core.User'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]


DJOSER = {
    'LOGIN_FIELD':'email',
    'USER_CREATE_PASSWORD_RETYPE':False,
    'SEND_ACTIVATION_EMAIL':False,
    'ACTIVATION_URL':'activate/{uid}/{token}',
    'SERIALIZERS': {
        'user_create': 'core.serializers.UserCreateSerializer',
        'current_user': 'core.serializers.UserSerializer'
    }

}
# Email / Site settings
DOMAIN = os.getenv('DOMAIN', 'localhost:3000').replace('https://', '').replace('http://', '')
SITE_NAME = os.getenv('SITE_NAME', 'Nepecom')


#FOR SMTP
#email host 
EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = int(os.getenv("EMAIL_PORT",587))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() in ("true", "1", "t")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")

FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173')

EMAIL_TIMEOUT = 30

#for admin site mail
ADMINS=[
    ('Rajesh Ghimire','rajesh.ghimire200@gmail.com')
]

CELERY_BROKER_URL='redis://localhost:6379/1'

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'notify-daily': {
        'task': 'playground.tasks.notify_customer',
        'schedule': timedelta(seconds=5), # every day at 9:00 AM
        'args': ('Hello',),
    },
}



CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/2",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}


LOGGING={
    'version':1,
    'disable_existing_loggers':False,
    'handlers':{
        "console":{
            'class':'logging.StreamHandler',
        },
        'file':{
            'class':'logging.FileHandler',
            'filename':'general.log',
            'formatter':'verbose'
        }
    },
    'loggers':{
        '':{
            'handlers':['console','file'],
            'level':os.environ.get('DJANGO_LOG_LEVEL','INFO')
        }
    },
    'formatters':{
        'verbose':{
            'format':'{asctime}({levelname})-{name}-{message}',
            'style':'{'
        }
    }
}
ALLOWED_HOSTS = [
    "nepecom.onrender.com",  # your Render URL
    "www.nepecom.onrender.com",
    "nepecom.nepecom.workers.dev",
   
]


CORS_ALLOWED_ORIGINS = [
    'https://nepecom.nepecom.workers.dev',
]


DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get("CLOUDINARYNAME"),
    'API_KEY': os.environ.get("CLOUDINARYAPIKEY"),
    'API_SECRET': os.environ.get("CLOUDINARYSECRETKEY"),
}
